services:
  - type: web
    name: hostelite-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build:shared && npm run build:backend
    startCommand: node apps/backend/dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
